[package]
name = "spot-service"
version = "0.1.0"
edition.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
axum-extra = { workspace = true }
cookie = { workspace = true }
geo = { workspace = true }
tzf-rs = { workspace = true }
reqwest = { workspace = true }
dotenvy = { workspace = true }
garde = { workspace = true }

async-nats = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

bus = { path = "../../../bus" }
shared = { path = "../../../shared" }