-- `app_user.email` cannot be NULL, so say so.
--
-- The column was nullable from the start, which made `ViewUser::email` an
-- `Option<String>` and `OwnerViewUser::email` an `Option` that no code path could ever
-- produce a `None` for:
--
--   * every row is created by `UserRegistered`, whose `email` is a `String`, applied
--     through `ViewUserRepository::upsert`;
--   * `UserUpdated` only ever reaches `ViewUserRepository::patch`, which is an `UPDATE`
--     and cannot bring a row into existence.
--
-- An `Option` that is never `None` is noise at every call site, and in a projection it
-- reads like the per-caller scoping this read model deliberately no longer does. The
-- constraint is what makes the `String` honest rather than assumed.
--
-- A separate file rather than an edit to 0001: `sqlx::migrate!` checksums what it has
-- applied, so editing an applied migration in place breaks every existing database.
-- Nothing is a source of truth here — if this ever fails on rows that predate the
-- reasoning above, drop the read model and re-project it from the log.
ALTER TABLE app_user ALTER COLUMN email SET NOT NULL;
